name: Setup node and pnpm
description: >
  Configures devbox, node, pnpm, cache, performs pnpm install

inputs:
  pnpm-run-install:
    description: Whether to run pnpm install
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Install nix
      uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1

    - name: cachix cache
      uses: cachix/cachix-action@38b082610b782e7e93e209c35fd730d399dee866 # v17
      with:
        name: devenv

    - name: Install devenv.sh
      shell: bash
      run: nix profile add nixpkgs#devenv

    - name: Build the devenv shell and run any pre-commit hooks
      shell: bash
      run: devenv test

    - name: Run pnpm install
      if: ${{ inputs.pnpm-run-install == 'true' }}
      shell: devenv shell bash -- -e {0}
      run: pnpm install --frozen-lockfile
