plugins:
  - prettier-plugin-css-order
  - prettier-plugin-tailwindcss
  - "@ianvs/prettier-plugin-sort-imports"
cssDeclarationSorterOrder: smacss
importOrder:
  - "^react$"
  - "<TYPES>^(react)"
  - "^vite$"
  - "<TYPES>^(vite)"
  - "^clsx$"
  - "<TYPES>^(clsx)"
  - "^@*vite"
  - "<TYPES>^(@*vite)"
  - "<BUILTIN_MODULES>"
  - "<TYPES>^(node:)"
  - "<THIRD_PARTY_MODULES>"
  - "<TYPES>^([@a-z])"
  - "^~/(.*)$"
  - "<TYPES>^~/(.*)"
  - "^[.]"
  - "<TYPES>"
  - ""
  - "^(?!.*[.]css$)[./].*$"
  - ".css$"
importOrderTypeScriptVersion: 5.6.2
tailwindConfig: ./tailwind.config
tailwindFunctions:
  - clsx
  - cn
  - cva
  - cx
