apiVersion: apps/v1
kind: Deployment
metadata:
  name: vite-spa-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vite-spa-app
  template:
    metadata:
      labels:
        app: vite-spa-app
    spec:
      containers:
        - name: vite-spa-container
          image: ghcr.io/dsm23/dsm23-vite-spa-template:latest
          ports:
            - containerPort: 80
