apiVersion: v1
kind: Service
metadata:
  name: vite-spa-service
  annotations:
    # Depending on your cloud provider, you might need specific annotations
    # For example, on AWS:
    # service.beta.kubernetes.io/aws-load-balancer-type: "elb"
    # Or for a Network Load Balancer:
    # service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    # On Azure:
    # service.beta.kubernetes.io/azure-load-balancer-internal: "false"
    # On Google Cloud:
    # cloud.google.com/load-balancer-type: "External"
spec:
  selector:
    app: vite-spa-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
