name: Code Review
permissions:
  contents: read
  pull-requests: write
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  code-review:
    runs-on: ubuntu-24.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2
        with:
          egress-policy: audit
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          OPENAI_API_KEY: "${{ secrets.OPENAI_API_KEY }}"
