name: OSV-Scanner PR Scan

on:
  pull_request:
    branches:
      - main
  merge_group:
    branches:
      - main

permissions:
  contents: read

jobs:
  osv-scan-pr:
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@b00f71e051ddddc6e46a193c31c8c0bf283bf9e6 # v2.1.0
