name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null

jobs:
  extract-version:
    runs-on: ubuntu-latest
    outputs:
      playwright-version: ${{ steps.extract-playwright-version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Extract Playwright version
        id: extract-playwright-version
        run: |
          version=$(awk -F'"' '/"@playwright\/test": ".+"/{ gsub(/[^0-9.]/, "", $4); print $4; exit; }' package.json)
          echo "::set-output name=version::$version"

  playwright-tests:
    needs: extract-version
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4, 5, 6, 7, 8, 9]
        shardTotal: [9]
    container:
      image: mcr.microsoft.com/playwright:v${{ needs.extract-version.outputs.playwright-version }}-jammy
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: echo "node_version=$(cat .github/nodejs.version)" >> $GITHUB_ENV
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run Playwright tests
        run: pnpm playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
        env:
          # Required for firefox
          HOME: /root
      - name: Upload playwright report to GitHub Actions Artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.shardIndex }}
          path: playwright-report/
          retention-days: 1
